### ISSUE TITLE
Hi there so i have this issue, and i cant resolve it, please help :)

### ISSUE THREAD

**Issue by HelenaRodrigues1986** [KunMinX/Smooth-Navigation#22]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appqueen.quizzmaster, PID: 19760
    java.lang.IllegalArgumentException: Navigation action/destination com.appqueen.quizzmaster:id/action_mainFragment_to_quizzListFragment cannot be found from the current destination Destination(com.appqueen.quizzmaster:id/quizzListFragment) label=fragment_quizz_list class=com.appqueen.quizzmaster.view.poslogin.quizzlist.QuizzListFragment
        at androidx.navigation.NavController.navigate(NavController.kt:1540)
        at androidx.navigation.NavController.navigate(NavController.kt:1472)
        at androidx.navigation.NavController.navigate(NavController.kt:1454)
        at androidx.navigation.NavController.navigate(NavController.kt:1437)
        at com.appqueen.quizzmaster.view.shared.main.MainFragment.onClick(MainFragment.java:257)
        at android.view.View.performClick(View.java:7357)
        at android.widget.TextView.performClick(TextView.java:14263)
        at android.view.View.performClickInternal(View.java:7323)
        at android.view.View.access$3200(View.java:849)
        at android.view.View$PerformClick.run(View.java:27895)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by HelenaRodrigues1986** [comment]
*app build JAVA at Android Studio, it hapends when user clicks at buttons on the mainfragment
