### ISSUE TITLE
java.lang.IllegalArgumentException: Navigation action

### ISSUE THREAD

**Issue by ff-frida** [KunMinX/Smooth-Navigation#8]
`2021-04-25 22:42:14.737 19593-19593/com.kunminx.smoothnavigation E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kunminx.smoothnavigation, PID: 19593
    java.lang.IllegalArgumentException: Navigation action/destination com.kunminx.smoothnavigation:id/action_listFragment_to_detailFragment cannot be found from the current destination Destination(com.kunminx.smoothnavigation:id/detailFragment) label=DetailFragment class=com.kunminx.puremusic.ui.DetailFragment
        at androidx.navigation.NavController.navigate(NavController.java:938)
        at androidx.navigation.NavController.navigate(NavController.java:875)
        at androidx.navigation.NavController.navigate(NavController.java:861)
        at androidx.navigation.NavController.navigate(NavController.java:849)
        at com.kunminx.puremusic.ui.ListFragment.lambda$onCreateView$0$ListFragment(ListFragment.java:60)
        at com.kunminx.puremusic.ui.-$$Lambda$ListFragment$4BN03aTrC9t10SJQdwnHqZnZ3TQ.onItemClick(Unknown Source:4)
        at com.kunminx.puremusic.ui.base.adapter.BaseBindingAdapter.lambda$onCreateViewHolder$1$BaseBindingAdapter(BaseBindingAdapter.java:75)
        at com.kunminx.puremusic.ui.base.adapter.-$$Lambda$BaseBindingAdapter$8LeqcfLWURSbEo3pVSDDYsfV3jg.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7184)
        at android.view.View.performClickInternal(View.java:7161)
        at android.view.View.access$3500(View.java:818)
        at android.view.View$PerformClick.run(View.java:27677)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

在体验demo的时候点击列表，触发了这个异常。
红米8a，Android10.
没有修改过demo的任何代码。
我点击+添加动态，然后来回添加返回滑动。点击到某一条的时候就遇到这样情况了。

**Comment by KunMinX** [comment]
可能是在短时间内重复点击了同一个 item，解决办法是自行在外部为点击事件添加 “防抖” 效果（防止重复点击二次及以上）

参考资料：
https://github.com/mozilla-mobile/fenix/issues/15268
https://stackoverflow.com/questions/51060762/illegalargumentexception-navigation-destination-xxx-is-unknown-to-this-navcontr

**Comment by KunMinX** [comment]
可能是在短时间内重复点击了同一个 item，解决办法是自行在外部为点击事件添加 “防抖” 效果（防止重复点击二次及以上）

参考资料：
https://github.com/mozilla-mobile/fenix/issues/15268
https://stackoverflow.com/questions/51060762/illegalargumentexception-navigation-destination-xxx-is-unknown-to-this-navcontr

**Comment by ff-frida** [comment]
> 可能是在短时间内重复点击了同一个 item，解决办法是自行在外部为点击事件添加 “防抖” 效果（防止重复点击二次及以上）
> 
> 参考资料：
> [mozilla-mobile/fenix#15268](https://github.com/mozilla-mobile/fenix/issues/15268)
> https://stackoverflow.com/questions/51060762/illegalargumentexception-navigation-destination-xxx-is-unknown-to-this-navcontr

谢谢
